version: '3.8'
services:
    
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - rezinos_db:/db/
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=rezinos
      - MYSQL_USER=rezinos
      - MYSQL_PASSWORD=rezinopass

    command: 
      --sql-mode=""
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: on-failure

      
  redis:
    image: "redis:alpine"

  
  celery:
    build: .
    command: celery -A celery_worker.celery worker -P gevent --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - redis
      - mysql

  rezinos:
    build: .
    restart: always
    security_opt:    
      - seccomp=chrome.json
    ports:
      - "80:5000"
    depends_on:
      - mysql
    links:
      - "mysql:dbserver"
    environment:
      - SECRET_KEY=rezinosecret
      - MAIL_SERVER=smtp.mail.ru
      - MAIL_PORT=465
      - MAIL_USE_TLS=0
      - MAIL_USE_SSL=1
      - MAIL_USERNAME=chaikide@mail.ru
      - MAIL_PASSWORD=Akakiy00!
      - "DATABASE_URL = mysql+pymysql://rezinos:rezinopass@dbserver/rezinos"
      - "DEBUG = false"
    volumes:
      - rezinos_photos:/home/rezinos/app/base/static/assets/img/tire_photos
    depends_on:
      - mysql
      - redis
      
volumes:
  rezinos_photos:
  rezinos_db:

      
